import type { Metadata } from 'next'
import { Mali } from 'next/font/google'
import './globals.css'
import { cn } from '@/utils/css'

const caveat = Mali({ subsets: ['latin'], weight: ["200", "300", "400", "500", "600", "700"] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={cn(caveat.className, 'bg-quiet-abyss')}>{children}</body>
		</html>
	)
}
